# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-07 11:36
from __future__ import unicode_literals

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_template_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitem',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
