# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-07 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_auto_20170807_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitemcomment',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
