# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_templateitemcomment_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
