# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_template_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
