# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_templateitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
