# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-02-08 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_template_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitemcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='templateitemcomment',
            name='item',
        ),
        migrations.DeleteModel(
            name='TemplateItemComment',
        ),
    ]
