# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
