# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_auto_20170809_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
