# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_checklistevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistevent',
            name='css_class',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
