# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-16 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_template_is_active'),
        ('checklists', '0006_checklistitemcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='original_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.TemplateItem'),
        ),
    ]
