# Generated by Django 3.2.20 on 2023-12-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0009_auto_20180208_1111'),
        ('checklists', '0007_checklistitem_original_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_not_applicable',
            field=models.BooleanField(default=False, help_text='Not Applicable'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.template'),
        ),
    ]
