# Generated by Django 3.2.20 on 2024-04-08 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklists', '0008_auto_20240408_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='bulk_mark_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='bulk_mark_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_bulk_mark_completed', to=settings.AUTH_USER_MODEL),
        ),
    ]
